### ISSUE TITLE
fallback if Javascript disabled

### ISSUE THREAD

**Issue by Wooody82** [mindgruve/scroll-animations#1]
Hi,
Text is not showing if javascript disabled. is there anyway to show it if js disabled? 

Thanks
  
Updated:: I think I solve it by adding no-js and some js,css code..

 $( "html" ).removeClass( "no-js" ).addClass( "js" );

.no-js [data-animation]{
  opacity: 1;
}

**Comment by cavemon** [comment]
@malasaad82 beat me to it! that is the solution!
